# 最好把imagepullpolicy改成always，以便开发时系统刷新代码
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-apiserver-service-controller
  namespace: cicd-apiserver
  labels:
    api: cicd-apiserver-service
    controller: "true"
spec:
  selector:
    matchLabels:
      api: cicd-apiserver-service
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: cicd-apiserver-service
        controller: "true"
    spec:
      containers:
      - name: controller
        image: jackyzhangfd/cicd-apiserver-builder:1.0
        imagePullPolicy: Always
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: cicd-apiserver-service
